version: "3"
services:
  server:
    container_name: server
    build: .
    ports:
      - 5000:3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
  